### ISSUE TITLE
correct recipe to build meraki-uboot outside of openwrt build mechanism

### ISSUE THREAD

**Issue by greghutchins** [riptidewave93/meraki-uboot#1]
Hello Chris,  

I don't want to brick my Meraki so hoping you can comment on the following steps to build u-boot:
1. export ARCH=arm
2. export CROSS_COMPILE=/home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.5.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-
3. export STAGING_DIR=/home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir
4. make ipq40xx_cdp_config
5. make

I had the following issue with the build during compilation phase:
make -C arch/arm/cpu/armv7/qca/
gpio.o: In function `__raw_writesb':
/home/greg/meraki_33/meraki-uboot/include/asm/io.h:79: multiple definition of `__raw_writesb'
timer.o:/home/greg/meraki_33/meraki-uboot/include/asm/io.h:79: first defined here

This was fixed by changing:

extern inline void __raw_writesb(unsigned int addr, const void *data, int bytelen)

to:

static inline void __raw_writesb(unsigned int addr, const void *data, int bytelen)

I had the following issue with the build during the linking phase:
/home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.5.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-gcc arch/arm/cpu/u-boot.lds
Linking u-boot...
/home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.5.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-ld: error: /home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.5.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/5.5.0/libgcc.a(_udivmoddi4.o) uses VFP register arguments, u-boot does not
/home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.5.0_musl_eabi/bin/arm-openwrt-linux-muslgnueabi-ld: failed to merge target specific data of file /home/greg/meraki_33/LEDE-MR33/openwrt/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.5.0_musl_eabi/lib/gcc/arm-openwrt-linux-muslgnueabi/5.5.0/libgcc.a(_udivmoddi4.o)
make: *** [u-boot] Error 1

This was fixed by removing "-msoft-float" from arch/arm/cpu/armv7/config.mk:PLATFORM_RELFLAGS.

I am wondering if you configured your build differently, or used a different method.  Next step is to
cross my fingers and burn the generated uboot.bin into flash...

Thanks for your help -- Greg

**Comment by riptidewave93** [comment]
Tagging in @chunkeey for this, as he did the U-Boot magic for the MR33.

**Comment by greghutchins** [comment]
thanks

**Comment by chunkeey** [comment]
> I have something that compiles and runs now but does not quite match the
mr33-uboot.bin image provided by Chris Blake.

Meraki purposely #undef'd or removed some of the options (i.e. networking+tftp and loadb/y/z commands) that would have made it possible to upload an external firmware from their own
u-boot.

If you want to make your own u-boot image and want all these features, you'll have to edit the include/configs/ipq40xx_cdp.h file and add:

    #define CONFIG_CMD_LOADB
    #define CONFIG_CMD_MISC
    #define CONFIG_CMD_TFTPSRV
    #define CONFIG_LZMA

and remove

    #undef CONFIG_CMD_NET

**Comment by greghutchins** [comment]
thanks for the help, working now
